# 온보딩 (4) : numpy
* 파이썬으로 과학 연산을 쉽고 빠르게 할 수 있게 만든 패키지
* 0321 + 0328

## 1차원 데이터

In [7]:
import numpy as np

In [8]:
list1 = [i for i in range(1, 11)]
arr1 = np.array(list1)
print(arr1)
print(type(arr1))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [9]:
list2 = [0, 1, 2, 5, 3, 4, 5, 6, 7, 8]
arr2 = np.array(list2)
arr2.dtype

dtype('int64')

In [10]:
arr3 = np.arange(0, 9, 1)
print(arr3)

[0 1 2 3 4 5 6 7 8]


In [11]:
import random
list = [random.randint(1, 100) for _ in range(10)]

## 2차원 데이터

In [12]:
list2 = [[1,2,3], [4,5,6], [7,8,9]]
print(np.array(list2).reshape(3, 3))
print(np.arange(9).reshape(3, 3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
str_a1 = np.array([random.randint(1, 100) for _ in range(10)])
print(str_a1.dtype)
str_a2 = str_a1.astype(float)
print(str_a2)
print(str_a2.dtype)

int64
[ 2. 55. 92. 38. 29. 48. 92. 20. 22.  7.]
float64


In [14]:
print(arr2)
print(arr2 + 200)

[0 1 2 5 3 4 5 6 7 8]
[200 201 202 205 203 204 205 206 207 208]


In [15]:
choi1 = np.array([1.1, 2.1, 3.1])
print(choi1.dtype)
choi1.astype(int)

float64


array([1, 2, 3])

In [16]:
choi1 = np.array([1, 2, 3])
print(choi1.dtype)
choi2 = choi1.astype(float)
choi2 = choi2 + 0.1
print(choi2)

int64
[1.1 2.1 3.1]


## 행렬/벡터 함수

In [17]:
print(np.linspace(1, 100, 11)) # 등간격 배열 생성
print(np.ones(5)) # 1벡터 생성
print(np.zeros(3)) # 영벡터 생성

print(np.linspace(0, np.pi, 20))

[  1.   10.9  20.8  30.7  40.6  50.5  60.4  70.3  80.2  90.1 100. ]
[1. 1. 1. 1. 1.]
[0. 0. 0.]
[0.         0.16534698 0.33069396 0.49604095 0.66138793 0.82673491
 0.99208189 1.15742887 1.32277585 1.48812284 1.65346982 1.8188168
 1.98416378 2.14951076 2.31485774 2.48020473 2.64555171 2.81089869
 2.97624567 3.14159265]


In [18]:
1 in np.arange(3)
arr1 = np.array([random.randint(1, 100) for _ in range(10)])
print(np.where(arr1 == 1))

(array([], dtype=int64),)


In [19]:
print(1 in arr1)
print(9 in arr1)

False
False


In [20]:
print(np.diag([10, 11, 12, 13, 14]))
print(np.eye(5))

mat = np.array([[1, 2, 3],[4, 5, 6]])
print(np.transpose(mat))

[[10  0  0  0  0]
 [ 0 11  0  0  0]
 [ 0  0 12  0  0]
 [ 0  0  0 13  0]
 [ 0  0  0  0 14]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1 4]
 [2 5]
 [3 6]]


## 연산용 함수

In [21]:
arr4 = np.arange(5)
info = [arr4.sum(), arr4.mean(), arr4.std(), arr4.var(),
        arr4.min(), arr4.max(), arr4.cumsum(), arr4.cumprod()]
print(info)

[10, 2.0, 1.4142135623730951, 2.0, 0, 4, array([ 0,  1,  3,  6, 10]), array([0, 0, 0, 0, 0])]


In [22]:
A = np.array([random.randint(1, 20) for _ in range(4)]).reshape(2, 2)
B = np.array([random.randint(1, 20) for _ in range(4)]).reshape(2, 2)
print(A)
print(B)

# 행렬곱
print(A.dot(B))

# 역행렬
np.linalg.inv(A)

# 행렬식
np.linalg.det(B)

# 전치
np.transpose(A.dot(B))

[[ 3 19]
 [ 6 10]]
[[14  1]
 [16 16]]
[[346 307]
 [244 166]]


array([[346, 244],
       [307, 166]])

## 배열 : 인덱싱

In [23]:
a2 = np.array([i for i in range(10, 100, 10)]).reshape(3,3)
print(a2)
print(a2[0,2])
if a2[0,2] > 0:
    a2[0,2] = 10
print(a2)
print(a2[2:])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
30
[[10 20 10]
 [40 50 60]
 [70 80 90]]
[[70 80 90]]


In [24]:
print(np.array([i for i in range(1, 11)]).reshape(2, 5))
arr3 = np.linspace(1, 10, 10).reshape(2, 5)
print(arr3)
print(type(arr3))
print(arr3[0, :])
print(arr3[:, 0])
print(arr3[0].sum())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
<class 'numpy.ndarray'>
[1. 2. 3. 4. 5.]
[1. 6.]
15.0


In [25]:
arr5 = np.array([i for i in range(1, 10)]).reshape(3, 3)
print(arr5.dtype)
arr5[2,:] = [1, 2, 3]
# arr5[,2] -> 이렇게는 못 쓴다.
arr5[:,2]

int64


array([3, 6, 3])

In [26]:
arr6 = np.array([i for i in range(1, 100, 11)]).reshape(3, 3)
print(arr6.sum(axis=0))
print(arr6.sum(axis=1))

[102 135 168]
[ 36 135 234]


In [27]:
arr6 = np.linspace(1, 10, 10)
print(f"before : {arr6}")
arr6.shape = (2,-1)
print(f"before : {arr6}")

before : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
before : [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [28]:
print(arr6[1,2])
print(arr6[0,:])
print(arr6.sum(axis = 0))
print(arr6.sum(axis = 1))
print(arr6[arr6 > 3])
print(arr6[(arr6 % 2) == 0])
print(arr6[(arr6 % 2) == 1])

8.0
[1. 2. 3. 4. 5.]
[ 7.  9. 11. 13. 15.]
[15. 40.]
[ 4.  5.  6.  7.  8.  9. 10.]
[ 2.  4.  6.  8. 10.]
[1. 3. 5. 7. 9.]


## 배열 : 슬라이싱

### 1차원 데이터

In [29]:
b1 = np.array([i for i in range(0, 60, 10)])
b1

array([ 0, 10, 20, 30, 40, 50])

In [30]:
b1[2:5] = np.array([25, 35, 45])
print(b1)

[ 0 10 25 35 45 50]


In [31]:
b1[3:6] = 60
print(b1)

[ 0 10 25 60 60 60]


### 2차원 데이터

In [32]:
b2 = np.arange(10, 100, 10).reshape(3,3)
print(b2, end="\n\n")
print(b2[1], end="\n\n")
print(b2[0:2], end="\n\n")
print(b2[1][0:2], end="\n\n")

b2[0:2, 1:3] = np.array([[2, 3], [4, 5]])
print(b2)

[[10 20 30]
 [40 50 60]
 [70 80 90]]

[40 50 60]

[[10 20 30]
 [40 50 60]]

[40 50]

[[10  2  3]
 [40  4  5]
 [70 80 90]]


# 온보딩 (5) : pandas

* 넘파이를 기반으로 만들어진 라이브러리
* 패널 형식의 데이터를 다루는 라이브러리

## 판다스의 구조
1. Series
    * 1차원 구조의 데이터
    * 벡터 형태
2. Dataframe
    * 2차원 구조의 데이터
    * pandas 라이브러리의 dataframe 형식으로 가져와 data를 저장 및 가공
3. Panel
    * 3차원 구조의 데이터

In [33]:
import pandas as pd
import numpy as np

/tmp/ipykernel_11960/2162656668.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


## Series()
* 시퀸스 데이터가 들어가야 함
* 주로 리스트를 많이 씀.
* 꼭 자료형이 같을 필요가 없음.

In [34]:
s1 = pd.Series([i for i in range(10, 60, 10)])
print(s1)
print(s1.index)

0    10
1    20
2    30
3    40
4    50
dtype: int64
RangeIndex(start=0, stop=5, step=1)


In [35]:
s1.values

array([10, 20, 30, 40, 50])

In [36]:
# 리스트 타입으로 정의. 자료형이 다를 수도 있음.
s2 = pd.Series(['a', 'b', 'c', 'd', 1, 2, 3])
s2

0    a
1    b
2    c
3    d
4    1
5    2
6    3
dtype: object

### missing data
* pandas에서는 지원하지 않음
* numpy 객체의 멤버변수인 nan을 써야 함.

In [37]:
s3 = pd.Series([np.nan, 10, 30])
s3

0     NaN
1    10.0
2    30.0
dtype: float64

### Series()를 통한 데이터 생성
* 함수의 구조 = ```pd.Series(seq_data, index=index_seq)```
* index_seq를 집어넣어서 데이터를 만들어보자.
* ex. 어느 가게의 날짜별 판매량을 pandas의 Series 형식으로 입력해보자.
* 판매량 데이터가 없는 날은 np.nan으로 설정.

In [38]:
index_date = ['2018-10-07', '2018-10-08', '2018-10-09', '2018-10-10']
s4 = pd.Series([200, 195, np.nan, 205], index=index_date)
s4

2018-10-07    200.0
2018-10-08    195.0
2018-10-09      NaN
2018-10-10    205.0
dtype: float64

In [39]:
s5 = pd.Series({'국어':100, '영어':95, '수학':90})
s5

국어    100
영어     95
수학     90
dtype: int64

In [40]:
s5.index

Index(['국어', '영어', '수학'], dtype='object')

In [41]:
s5.values

array([100,  95,  90])

## 날짜변수 다루기
* 원하는 날짜를 자동으로 생성해주는 함수
* ```pd.date_range()``` 사용해서 만들어보기

In [42]:
TODAY = '2019-01-01'
FINISH = '2019-01-07'

In [43]:
pd.date_range(start = TODAY, end= '2019-01-07')

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')

날짜 입력 시 기입 방법
* yyyy-mm-dd 방식 (제일 기본)
* yyyy/mm/dd
* yyyy.mm.dd
* mm-dd-yyyy
* mm/dd/yyyy
* mm.dd.yyyy

In [44]:
pd.date_range(start='2019-01-01', end='2019/01/07')

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')

In [45]:
pd.date_range(start='01-01-2019', end='01-07-2019')

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')

In [46]:
pd.date_range(start='01/01/2019', end='01/07/2019')

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')

In [47]:
pd.date_range(start='01.01.2019', end='01.07.2019')

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')

### 날짜 조정 함수

In [48]:
# 오늘부터 7일 후의 날짜를 가져오기.
today_date = pd.to_datetime('today').date()
later_date = today_date + pd.Timedelta(days=7)

pd.date_range(start=today_date, end=later_date)

DatetimeIndex(['2024-04-04', '2024-04-05', '2024-04-06', '2024-04-07',
               '2024-04-08', '2024-04-09', '2024-04-10', '2024-04-11'],
              dtype='datetime64[ns]', freq='D')

### date_range() : periods
* 파라미터 end와 같이 쓰면 안됨

In [49]:
pd.date_range(start = pd.to_datetime('today').date(), periods=8)

DatetimeIndex(['2024-04-04', '2024-04-05', '2024-04-06', '2024-04-07',
               '2024-04-08', '2024-04-09', '2024-04-10', '2024-04-11'],
              dtype='datetime64[ns]', freq='D')

In [50]:
pd.date_range(start=TODAY, end=FINISH, freq='D')

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')

### date_range() : freq

In [51]:
# 이틀 간 간격: freq='2D'로 설정
pd.date_range(start = pd.to_datetime('today').date(), periods=8, freq='2D')

DatetimeIndex(['2024-04-04', '2024-04-06', '2024-04-08', '2024-04-10',
               '2024-04-12', '2024-04-14', '2024-04-16', '2024-04-18'],
              dtype='datetime64[ns]', freq='2D')

달력 만들기: freq='W' 사용

In [52]:
print(pd.date_range(start=TODAY, periods=4, freq='W'))
print(pd.date_range(start=TODAY, periods=4, freq='W-SUN'))
print(pd.date_range(start=TODAY, periods=4, freq='W-MON'))
print(pd.date_range(start=TODAY, periods=4, freq='W-TUE'))
print(pd.date_range(start=TODAY, periods=4, freq='W-WED'))

DatetimeIndex(['2019-01-06', '2019-01-13', '2019-01-20', '2019-01-27'], dtype='datetime64[ns]', freq='W-SUN')
DatetimeIndex(['2019-01-06', '2019-01-13', '2019-01-20', '2019-01-27'], dtype='datetime64[ns]', freq='W-SUN')
DatetimeIndex(['2019-01-07', '2019-01-14', '2019-01-21', '2019-01-28'], dtype='datetime64[ns]', freq='W-MON')
DatetimeIndex(['2019-01-01', '2019-01-08', '2019-01-15', '2019-01-22'], dtype='datetime64[ns]', freq='W-TUE')
DatetimeIndex(['2019-01-02', '2019-01-09', '2019-01-16', '2019-01-23'], dtype='datetime64[ns]', freq='W-WED')


In [53]:
# 개선된 코드

dates = ['W', 'W-SUN', 'W-MON', 'W-TUE', 'W-WED', 'W-FRI']
for date in dates:
    print(pd.date_range(start=TODAY, periods=4, freq=date))

DatetimeIndex(['2019-01-06', '2019-01-13', '2019-01-20', '2019-01-27'], dtype='datetime64[ns]', freq='W-SUN')
DatetimeIndex(['2019-01-06', '2019-01-13', '2019-01-20', '2019-01-27'], dtype='datetime64[ns]', freq='W-SUN')
DatetimeIndex(['2019-01-07', '2019-01-14', '2019-01-21', '2019-01-28'], dtype='datetime64[ns]', freq='W-MON')
DatetimeIndex(['2019-01-01', '2019-01-08', '2019-01-15', '2019-01-22'], dtype='datetime64[ns]', freq='W-TUE')
DatetimeIndex(['2019-01-02', '2019-01-09', '2019-01-16', '2019-01-23'], dtype='datetime64[ns]', freq='W-WED')
DatetimeIndex(['2019-01-04', '2019-01-11', '2019-01-18', '2019-01-25'], dtype='datetime64[ns]', freq='W-FRI')


시간 자동 생성 (개선된 코드)

In [54]:

CURTIME = '2019-01-01 08:00'
pd.date_range(start = CURTIME, periods=10, freq='BH')

# BH는 하루를 의미. 
# BH 대신 bh를 쓰라고 권고 (deprecated)

/tmp/ipykernel_11960/4096033035.py:2: FutureWarning: 'BH' is deprecated and will be removed in a future version, please use 'bh' instead.
  pd.date_range(start = CURTIME, periods=10, freq='BH')


DatetimeIndex(['2019-01-01 09:00:00', '2019-01-01 10:00:00',
               '2019-01-01 11:00:00', '2019-01-01 12:00:00',
               '2019-01-01 13:00:00', '2019-01-01 14:00:00',
               '2019-01-01 15:00:00', '2019-01-01 16:00:00',
               '2019-01-02 09:00:00', '2019-01-02 10:00:00'],
              dtype='datetime64[ns]', freq='bh')

시간 간격 조정

In [55]:
# period 다르게 해보기 (개선된 코드)

CURTIME = '2019-01-01 '
times = ['08:00', '07:00', '09:00', '10:00', '11:00']
period = [10, 10, 10, 5, 5]
for i in range(len(times)):
    print(pd.date_range(start = CURTIME + times[i], periods = period[i], freq='bh'))

DatetimeIndex(['2019-01-01 09:00:00', '2019-01-01 10:00:00',
               '2019-01-01 11:00:00', '2019-01-01 12:00:00',
               '2019-01-01 13:00:00', '2019-01-01 14:00:00',
               '2019-01-01 15:00:00', '2019-01-01 16:00:00',
               '2019-01-02 09:00:00', '2019-01-02 10:00:00'],
              dtype='datetime64[ns]', freq='bh')
DatetimeIndex(['2019-01-01 09:00:00', '2019-01-01 10:00:00',
               '2019-01-01 11:00:00', '2019-01-01 12:00:00',
               '2019-01-01 13:00:00', '2019-01-01 14:00:00',
               '2019-01-01 15:00:00', '2019-01-01 16:00:00',
               '2019-01-02 09:00:00', '2019-01-02 10:00:00'],
              dtype='datetime64[ns]', freq='bh')
DatetimeIndex(['2019-01-01 09:00:00', '2019-01-01 10:00:00',
               '2019-01-01 11:00:00', '2019-01-01 12:00:00',
               '2019-01-01 13:00:00', '2019-01-01 14:00:00',
               '2019-01-01 15:00:00', '2019-01-01 16:00:00',
               '2019-01-02 09:00:00', '2019-01

분 간격 생성

In [56]:
# freq 다르게 해보기 (개선된 코드)

CURTIME = '2019-01-01 '
times = ['08:00', '07:00', '09:00', '10:00', '11:00', '12:00']
frequency = ['30min', '30T', '10T', '40T', '60T', '130T']
for i in range(len(times)):
    print(pd.date_range(start = CURTIME + times[i], periods = 4, freq=frequency[i]))

DatetimeIndex(['2019-01-01 08:00:00', '2019-01-01 08:30:00',
               '2019-01-01 09:00:00', '2019-01-01 09:30:00'],
              dtype='datetime64[ns]', freq='30min')
DatetimeIndex(['2019-01-01 07:00:00', '2019-01-01 07:30:00',
               '2019-01-01 08:00:00', '2019-01-01 08:30:00'],
              dtype='datetime64[ns]', freq='30min')
DatetimeIndex(['2019-01-01 09:00:00', '2019-01-01 09:10:00',
               '2019-01-01 09:20:00', '2019-01-01 09:30:00'],
              dtype='datetime64[ns]', freq='10min')
DatetimeIndex(['2019-01-01 10:00:00', '2019-01-01 10:40:00',
               '2019-01-01 11:20:00', '2019-01-01 12:00:00'],
              dtype='datetime64[ns]', freq='40min')
DatetimeIndex(['2019-01-01 11:00:00', '2019-01-01 12:00:00',
               '2019-01-01 13:00:00', '2019-01-01 14:00:00'],
              dtype='datetime64[ns]', freq='60min')
DatetimeIndex(['2019-01-01 12:00:00', '2019-01-01 14:10:00',
               '2019-01-01 16:20:00', '2019-01-01 18:30:00'],
  

/tmp/ipykernel_11960/3022237276.py:7: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  print(pd.date_range(start = CURTIME + times[i], periods = 4, freq=frequency[i]))


초 간격 생성

In [57]:
CURTIME = '2019-01-01 '
times = ['08:00', '07:00', '09:00', '10:00', '11:00', '12:00']
for i in range(len(times)):
    print(pd.date_range(start = CURTIME + times[i], periods = 4, freq='10s'))

DatetimeIndex(['2019-01-01 08:00:00', '2019-01-01 08:00:10',
               '2019-01-01 08:00:20', '2019-01-01 08:00:30'],
              dtype='datetime64[ns]', freq='10s')
DatetimeIndex(['2019-01-01 07:00:00', '2019-01-01 07:00:10',
               '2019-01-01 07:00:20', '2019-01-01 07:00:30'],
              dtype='datetime64[ns]', freq='10s')
DatetimeIndex(['2019-01-01 09:00:00', '2019-01-01 09:00:10',
               '2019-01-01 09:00:20', '2019-01-01 09:00:30'],
              dtype='datetime64[ns]', freq='10s')
DatetimeIndex(['2019-01-01 10:00:00', '2019-01-01 10:00:10',
               '2019-01-01 10:00:20', '2019-01-01 10:00:30'],
              dtype='datetime64[ns]', freq='10s')
DatetimeIndex(['2019-01-01 11:00:00', '2019-01-01 11:00:10',
               '2019-01-01 11:00:20', '2019-01-01 11:00:30'],
              dtype='datetime64[ns]', freq='10s')
DatetimeIndex(['2019-01-01 12:00:00', '2019-01-01 12:00:10',
               '2019-01-01 12:00:20', '2019-01-01 12:00:30'],
            

### 달 조정

In [58]:
periods = [3, 4, 10]
for p in periods:
    print(pd.date_range(start=TODAY, periods=p, freq='YS'))

DatetimeIndex(['2019-01-01', '2020-01-01', '2021-01-01'], dtype='datetime64[ns]', freq='YS-JAN')
DatetimeIndex(['2019-01-01', '2020-01-01', '2021-01-01', '2022-01-01'], dtype='datetime64[ns]', freq='YS-JAN')
DatetimeIndex(['2019-01-01', '2020-01-01', '2021-01-01', '2022-01-01',
               '2023-01-01', '2024-01-01', '2025-01-01', '2026-01-01',
               '2027-01-01', '2028-01-01'],
              dtype='datetime64[ns]', freq='YS-JAN')


### 응용 문제
* date_range() 이용, Series()의 index 지정

In [59]:
d1 = pd.to_datetime('2019-03-01').date()

date_index = pd.date_range(start = d1, end = d1 + pd.Timedelta(days = 4))
pd.Series([51, 62, 55, 49, 48], date_index)

2019-03-01    51
2019-03-02    62
2019-03-03    55
2019-03-04    49
2019-03-05    48
Freq: D, dtype: int64

## DataFrame()
* 표와 같은 2차원 데이터
* ```DataFrame(data 변수명, index = index 변수명, columns = column list 타입 변수명)```
* 리스트, 딕셔너리, 넘파이 등등을 넣을 수 있음
* index와 columns는 선택사항.
    * 입력하지 않을 경우 자동으로 0부터 숫자가 생성

In [60]:
DATA = np.array([i for i in range(1, 10)]).reshape(3,3)
pd.DataFrame(DATA)

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

인덱스와 컬럼 조정

In [61]:
data = np.array([i for i in range(10, 100, 10)]).reshape(3,3)
column = [chr(i) for i in range(65, 68)]

d1 = pd.to_datetime('2019-09-01').date()
d2 = d1 + pd.Timedelta(days=2)
pd.DataFrame(data, index=pd.date_range(start = d1, end = d2), columns=column)

A   B   C
2019-09-01  10  20  30
2019-09-02  40  50  60
2019-09-03  70  80  90

딕셔너리로 dataframe 생성

In [62]:
dict = {'연도' : [2015, 2016, 2016, 2017, 2017],
       '지사' : ['한국', '한국', '미국', '한국', '미국'],
       '고객 수' : [200, 250, 450, 300, 500]}

pd.DataFrame(dict)

연도  지사  고객 수
0  2015  한국   200
1  2016  한국   250
2  2016  미국   450
3  2017  한국   300
4  2017  미국   500

In [63]:
dict = {'연도' : [2015, 2016, 2016, 2017, 2017],
       '지사' : ['한국', '한국', '미국', '한국', '미국'],
       '고객 수' : [200, 250, 450, 300, 500]}
dict2 = {'지사' : ['한국', '한국', '미국', '한국', '미국'],
         '고객 수' : [200, 250, 450, 300, 500]}

pd.DataFrame(data = dict2, index = dict['연도'])

지사  고객 수
2015  한국   200
2016  한국   250
2016  미국   450
2017  한국   300
2017  미국   500

# 온보딩 (6) : 데이터연산

## Series 연산

In [64]:
s1 = pd.Series([i for i in range(1, 6, 1)])
s2 = pd.Series([i for i in range(10, 60, 10)])

print(s1 + s2)
print(s1 / s2)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    0.1
1    0.1
2    0.1
3    0.1
4    0.1
dtype: float64


In [65]:
# 자료 간 크기가 다른 경우
s1 = pd.Series([i for i in range(1, 7, 1)])
s2 = pd.Series([i for i in range(10, 60, 10)])

print(s1 + s2)

0    11.0
1    22.0
2    33.0
3    44.0
4    55.0
5     NaN
dtype: float64


In [66]:
# 빈 인덱스 채워주기
s1 = pd.Series([i for i in range(1, 5, 1)])
s2 = pd.Series([i for i in range(10, 60, 10)], index=[i for i in range(1, 6, 1)])
print(s1)
print(s2)
print(s1 + s2) # NaN이 생기게 된다.

0    1
1    2
2    3
3    4
dtype: int64
1    10
2    20
3    30
4    40
5    50
dtype: int64
0     NaN
1    12.0
2    23.0
3    34.0
4     NaN
5     NaN
dtype: float64


In [67]:
s1.add(s2, fill_value=0) # NaN이 생기지 않게 된다.

0     1.0
1    12.0
2    23.0
3    34.0
4    40.0
5    50.0
dtype: float64

## DataFrame 연산

In [71]:
df1 = pd.DataFrame({'A' : [i for i in range(1, 6, 1)], 
                    'B' : [i for i in range(10, 60, 10)], 
                    'C' : [i for i in range(100, 600, 100)]})
df2 = pd.DataFrame({'A' : [i for i in range(6, 9, 1)], 
                    'B' : [i for i in range(60, 90, 10)], 
                    'C' : [i for i in range(600, 900, 100)]})
print(df1)
print(df2)

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500
   A   B    C
0  6  60  600
1  7  70  700
2  8  80  800


In [79]:
# 연산자만 써서 계산시 반드시 NaN이 발생
print(df1 + df2)

# 메소드 add()를 써서 NaN 보완
df1.add(df2, fill_value = 0)

      A      B       C
0   7.0   70.0   700.0
1   9.0   90.0   900.0
2  11.0  110.0  1100.0
3   NaN    NaN     NaN
4   NaN    NaN     NaN


A      B       C
0   7.0   70.0   700.0
1   9.0   90.0   900.0
2  11.0  110.0  1100.0
3   4.0   40.0   400.0
4   5.0   50.0   500.0

In [138]:
# 데이터 연산 (평균 구하기)

df3 = pd.DataFrame({'봄' : [random.uniform(200, 350) for i in range(1, 6)],
                    '여름' : [random.uniform(500, 700) for i in range(1, 6)],
                    '가을' : [random.uniform(200, 380) for i in range(1, 6)],
                    '겨울' : [random.uniform(40, 160) for i in range(1, 6)]},
                    index = [i for i in range(2012, 2017)])
df3.mean()

봄     270.061238
여름    587.471157
가을    306.658522
겨울    116.582752
dtype: float64

### 행/열 전환

In [139]:
# 행과 열을 바꿔서 연산하기
# 1. transpose() 이용
df3_t = df3.transpose()
df3_t
print(df3_t.mean())

# 2. axis 이용
df3.mean(axis = 1)

2012    363.115515
2013    307.986925
2014    307.217314
2015    313.352783
2016    309.294550
dtype: float64


2012    363.115515
2013    307.986925
2014    307.217314
2015    313.352783
2016    309.294550
dtype: float64

### describe()

In [195]:
df3.describe()

봄          여름          가을          겨울
count    5.000000    5.000000    5.000000    5.000000
mean   270.061238  587.471157  306.658522  116.582752
std     32.521046   88.054815   48.405222   27.989746
min    213.652472  505.890975  246.940187   81.260153
25%    272.984510  518.182808  266.890284   94.064226
50%    283.935890  549.463826  317.413999  125.501476
75%    284.255773  670.144791  341.745454  133.878434
max    295.477544  693.673386  360.302688  148.209470