# numpy
* 파이썬으로 과학 연산을 쉽고 빠르게 할 수 있게 만든 패키지
* 0321 + 0328

## 1차원 데이터

In [1]:
import numpy as np

In [ ]:
list1 = [i for i in range(1, 11)]
arr1 = np.array(list1)
print(arr1)
print(type(arr1))

In [10]:
list2 = [0, 1, 2, 5, 3, 4, 5, 6, 7, 8]
arr2 = np.array(list2)
arr2.dtype

dtype('int64')

In [ ]:
arr3 = np.arange(0, 9, 1)
print(arr3)

In [14]:
import random
list = [random.randint(1, 100) for _ in range(10)]

## 2차원 데이터

In [12]:
list2 = [[1,2,3], [4,5,6], [7,8,9]]
print(np.array(list2).reshape(3, 3))
print(np.arange(9).reshape(3, 3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [25]:
str_a1 = np.array([random.randint(1, 100) for _ in range(10)])
print(str_a1.dtype)
str_a2 = str_a1.astype(float)
print(str_a2)
print(str_a2.dtype)

int64
[51. 20. 26. 36. 46. 37. 30. 14. 78. 91.]
float64


In [28]:
print(arr2)
print(arr2 + 200)

[0 1 2 5 3 4 5 6 7 8]
[200 201 202 205 203 204 205 206 207 208]


In [33]:
choi1 = np.array([1.1, 2.1, 3.1])
print(choi1.dtype)
choi1.astype(int)

array([1, 2, 3])

In [36]:
choi1 = np.array([1, 2, 3])
print(choi1.dtype)
choi2 = choi1.astype(float)
choi2 = choi2 + 0.1
print(choi2)

int64
[1.1 2.1 3.1]


## 행렬/벡터 함수

In [54]:
print(np.linspace(1, 100, 11)) # 등간격 배열 생성
print(np.ones(5)) # 1벡터 생성
print(np.zeros(3)) # 영벡터 생성

print(np.linspace(0, np.pi, 20))

[  1.   10.9  20.8  30.7  40.6  50.5  60.4  70.3  80.2  90.1 100. ]
[1. 1. 1. 1. 1.]
[0. 0. 0.]
[0.         0.16534698 0.33069396 0.49604095 0.66138793 0.82673491
 0.99208189 1.15742887 1.32277585 1.48812284 1.65346982 1.8188168
 1.98416378 2.14951076 2.31485774 2.48020473 2.64555171 2.81089869
 2.97624567 3.14159265]


In [60]:
1 in np.arange(3)
arr1 = np.array([random.randint(1, 100) for _ in range(10)])
print(np.where(arr1 == 1))

(array([], dtype=int64),)


In [63]:
print(1 in arr1)
print(9 in arr1)

False
False


In [75]:
print(np.diag([10, 11, 12, 13, 14]))
print(np.eye(5))

mat = np.array([[1, 2, 3],[4, 5, 6]])
print(np.transpose(mat))

[[10  0  0  0  0]
 [ 0 11  0  0  0]
 [ 0  0 12  0  0]
 [ 0  0  0 13  0]
 [ 0  0  0  0 14]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1 4]
 [2 5]
 [3 6]]


## 연산용 함수

In [76]:
arr4 = np.arange(5)
info = [arr4.sum(), arr4.mean(), arr4.std(), arr4.var(),
        arr4.min(), arr4.max(), arr4.cumsum(), arr4.cumprod()]
print(info)

[10, 2.0, 1.4142135623730951, 2.0, 0, 4, array([ 0,  1,  3,  6, 10]), array([0, 0, 0, 0, 0])]


In [85]:
A = np.array([random.randint(1, 20) for _ in range(4)]).reshape(2, 2)
B = np.array([random.randint(1, 20) for _ in range(4)]).reshape(2, 2)
print(A)
print(B)

# 행렬곱
print(A.dot(B))

# 역행렬
np.linalg.inv(A)

# 행렬식
np.linalg.det(B)

# 전치
np.transpose(A.dot(B))

[[ 6 19]
 [15 15]]
[[14 16]
 [15  9]]
[[369 267]
 [435 375]]


array([[369, 435],
       [267, 375]])

## 배열 : 인덱싱/슬라이싱

In [126]:
a2 = np.array([i for i in range(10, 100, 10)]).reshape(3,3)
print(a2)
print(a2[0,2])
if a2[0,2] > 0:
    a2[0,2] = 10
print(a2)
print(a2[2:])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
30
[[10 20 10]
 [40 50 60]
 [70 80 90]]
[[70 80 90]]


In [127]:
print(np.array([i for i in range(1, 11)]).reshape(2, 5))
arr3 = np.linspace(1, 10, 10).reshape(2, 5)
print(arr3)
print(type(arr3))
print(arr3[0, :])
print(arr3[:, 0])
print(arr3[0].sum())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
<class 'numpy.ndarray'>
[1. 2. 3. 4. 5.]
[1. 6.]
15.0
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 94]]


In [135]:
arr5 = np.array([i for i in range(1, 10)]).reshape(3, 3)
arr5[2,:] = [1, 2, 3]
# arr5[,2] -> 이렇게는 못 쓴다.
arr5[:,2]

array([3, 6, 3])

In [143]:
arr6 = np.array([i for i in range(1, 100, 11)]).reshape(3, 3)
print(arr6.sum(axis=0))
print(arr6.sum(axis=1))

[102 135 168]
[ 36 135 234]
